New property for RHSSO config file
mramendi/kie-docs pull request #172
Opened 2021-11-18 03:16 UTC by mramendi

2021-11-19 05:03 UTC, RishiRajAnand commented on doc-content/enterprise-only/integration/sso-remote-services-securing-proc.adoc
> +<property name="rg.uberfire.ext.security.keycloak.keycloak-config-file" value="$EAP_HOME/kie-git.json"/>
actual property name is '"org.uberfire.ext.security.keycloak.keycloak-config-file", we are missing an extra 'O' @mramendi

2021-11-19 05:08 UTC, RishiRajAnand commented on doc-content/enterprise-only/integration/sso-remote-services-securing-proc.adoc
> +. In the `_EAP_HOME_/standalone/configuration/standalone-full.xml` file, under the `<system-properties>` tag, add the following system property:
Can we also mention in some way that this is an optional property and if not added default "$EAP_HOME/kie-git.json" is considered ? @mramendi

2021-11-19 09:14 UTC, tomasdavidorg commented
![image](https://user-images.githubusercontent.com/4498639/142596835-6b82334e-fc8e-4776-9a26-5b2b2ffa0df6.png)
This part should be removed. (User should set just the `org.uberfire.ext.security.keycloak.keycloak-config-file` property.)

2021-11-19 12:56 UTC, tomasdavidorg requested changes
I agree with @RishiRajAnand  comments + see my comment about the removing the old part.

2021-11-19 14:42 UTC, tomasdavidorg approved these changes
Looks good to me. Thanks 🙂

2021-11-19 17:34 UTC, csherrar approved these changes
Apart from a couple of suggestions, looks good to me.

2021-11-19 17:34 UTC, csherrar commented on doc-content/enterprise-only/integration/sso-remote-services-securing-proc.adoc
> +To enable the {CENTRAL} to consume other remote services such as file systems and Git repositories using RH-SSO authentication, you must create a configuration file.
[Style] I think adding a comma as below will help with the long sentence or perhaps the middle content can be separated?

To enable the {CENTRAL} to consume other remote services, such as file systems and Git repositories using RH-SSO authentication, you must create a configuration file.

2021-11-19 17:34 UTC, csherrar commented on doc-content/enterprise-only/integration/sso-remote-services-securing-proc.adoc
> += Enabling access to external file system and Git repository services for {CENTRAL} using RH-SSO
[Style] Depending on the relation between these, suggest that "system" is pluralized or the title rephrased if external services applies to file system and git repositories. Examples:

Enabling access to external file systems and Git repository services with {CENTRAL} by using RH-SSO
Enabling access to external services such as file systems and Git repositories by using RH-SSO
Accessing external file systems and Git repository services with {CENTRAL} by using RH-SSO

2021-11-22 04:44 UTC, RishiRajAnand approved these changes

2021-11-22 04:44 UTC, RishiRajAnand commented
Looks good now Thanks @mramendi

2021-11-23 00:51 UTC, merged